### PR TITLE
Add example run to the README

### PR DESCRIPTION
**Pull request by jvehent**
This is a simple documentation item, but it raises a couple questions about the tool.
1. Which part of the text exactly is meant to be included into `certverifier/ExtendedValidation.cpp` ? I think it stops at `BuildCertChain` based on my reading of the cpp file, but that's not clear from the output of `ev-checker`.
2. When testing against `addons.mozilla.org`, I get `BuildCertChain failed: SEC_ERROR_UNKNOWN_ISSUER`. I verified the chain is valid and AMO uses an EV cert from digicert. Is this the expected output? The error message isn't very clear.

``` bash
$ openssl verify -untrusted DigiCertSHA2ExtendedValidationServerCA.pem -CAfile DigiCertECCExtendedValidationServerCA.pem addons.mozilla.org-20170921.crt
addons.mozilla.org-20170921.crt: OK
```

``` bash
$ ev-checker -c /tmp/chain -o 2.16.840.1.114412.2.1 -d "Digicert EV OID" -h addons.mozilla.org
// CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
"2.16.840.1.114412.2.1",
"Digicert EV OID",
SEC_OID_UNKNOWN,
{ 0xFD, 0xC8, 0x98, 0x6C, 0xFA, 0xC4, 0xF3, 0x5F, 0x1A, 0xCD, 0x51, 
  0x7E, 0x0F, 0x61, 0xB8, 0x79, 0x88, 0x2A, 0xE0, 0x76, 0xE2, 0xBA, 
  0x80, 0xB7, 0x7B, 0xD3, 0xF0, 0xFE, 0x5C, 0xEF, 0x88, 0x62 },
"MGwxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsT"
"EHd3dy5kaWdpY2VydC5jb20xKzApBgNVBAMTIkRpZ2lDZXJ0IEhpZ2ggQXNzdXJh"
"bmNlIEVWIFJvb3QgQ0E=",
"ApcHVgzUqeu/4nLx4JbYgg==",
BuildCertChain failed: SEC_ERROR_UNKNOWN_ISSUER
Peer's Certificate issuer is not recognized.
```

### CODE REVIEW

**Comment by mozkeeler** [comment]
Can you post a gist of the chain file you're using?

**Comment by jvehent** [comment]
Here it is: https://ulfr.io/f/amo_chain_20161012.txt
I verified the EE matches the certificate currently returned by https://addons.mozilla.org

**Comment by mozkeeler** [comment]
Here's the subjects/issuers I'm finding in that file:

```
subject= /businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=California/serialNumber=C2543436/street=650 Castro St Ste 300/postalCode=94041/C=US/ST=California/L=Mountain View/O=Mozilla Foundation/CN=addons.mozilla.org
issuer= /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
```

(amo end-entity - makes sense)

```
subject= /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
issuer= /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
```

(issued the first certificate - makes sense)

```
subject= /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert ECC Extended Validation Server CA
issuer= /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
```

(not the root we were expecting, so I think this one is the issue)

**Comment by jvehent** [comment]
Lesson learned: `openssl verify` doesn't do what I think it would do...
I fixed the chain: https://ulfr.io/f/amo_chain_20161012.txt
and now get the correct output:

```
$ ev-checker -c /tmp/amo_chain_20161012.txt -o 2.16.840.1.114412.2.1 -d "Digicert EV OID" -h addons.mozilla.org
// CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
"2.16.840.1.114412.2.1",
"Digicert EV OID",
SEC_OID_UNKNOWN,
{ 0x74, 0x31, 0xE5, 0xF4, 0xC3, 0xC1, 0xCE, 0x46, 0x90, 0x77, 0x4F, 
  0x0B, 0x61, 0xE0, 0x54, 0x40, 0x88, 0x3B, 0xA9, 0xA0, 0x1E, 0xD0, 
  0x0B, 0xA6, 0xAB, 0xD7, 0x80, 0x6E, 0xD3, 0xB1, 0x18, 0xCF },
"MGwxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsT"
"EHd3dy5kaWdpY2VydC5jb20xKzApBgNVBAMTIkRpZ2lDZXJ0IEhpZ2ggQXNzdXJh"
"bmNlIEVWIFJvb3QgQ0E=",
"AqxcJmoLQJuPC3nyrkYldw==",
Success!
```

I'll update the PR with this output. Per our discussion, I think it'd be nice to split out the cpp code output behind a flag so the tool only outputs `success` or `failed with error xyz` by default.

**Review by mozkeeler — APPROVED** [review]
Great - thanks!

**Pull request merged**
